services:
  - type: web
    name: atu-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y wkhtmltopdf
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000